### ISSUE TITLE
Add Title and Meta Description tags to Nexus pages

### ISSUE THREAD

**Issue by srfoster** [srfoster/nexus#27]
- These are basic SEO must haves!
- These go in `<head></head>` section.
- Titles are implemented like so: `<head><title>Example Title</title></head>`
- Meta Descriptions are implemented like so: `<head> <meta name="description" content="This is an example of a meta description. This will often show up in search results."></head>`
- Title best practices: https://moz.com/learn/seo/title-tag
- Meta Description best practices: https://moz.com/learn/seo/meta-description

**Comment by ldhandley** [comment]
Each page will have a unique title & meta description. For each page/page type, I've written a title and meta description below:

Homepage
http://nexus.codespells.org/
Title: "CodeSpells Nexus"
Meta Description: "Welcome to the Nexus! If you want to write and save spells that run on CodeSpells video games, you're in the right place."

Login Page
http://nexus.codespells.org/login
Title: "Login | CodeSpells Nexus"
Meta Description: "Log into the CodeSpells Nexus to create & save spells that you can cast in CodeSpells games and connect with other CodeSpells witches & wizards."

Signup Page
http://nexus.codespells.org/signup
Title: "Signup | CodeSpells Nexus"
Meta Description: "Sign up for a CodeSpells Nexus account and start writing and saving your spells today."

My Spells Page
http://nexus.codespells.org/spells
Title: "Spells | CodeSpells Nexus"
Meta Description: "Create and edit your spells. Spells that you make public can be cast inside of CodeSpells games."

Spells Details Page
http://nexus.codespells.org/spells/#
Title: "<spell-name> Spell | CodeSpells Nexus" (e.g. "Gloop and Loop! Spell | CodeSpells Nexus")
Meta Description: "<spell-description>" (e.g. "A spells that adds random force in a random direction on every tick.")

Friends Coming Soon Page
http://nexus.codespells.org/friends
Title: "Friends | CodeSpells Nexus"
Meta Description: "Connect with other witches & wizards of the CodeSpells community!"

Public Spells Page
http://nexus.codespells.org/gallery
Title: "Public Spells | CodeSpells Nexus"
Meta Description: "You can find all spells that have been made public here. These spells can be cast inside of CodeSpells game, or forked and edited!"

My Mage Page
http://nexus.codespells.org/wizards/#
Title: "<username> | CodeSpells Nexus" (e.g. "ldhandley | CodeSpells Nexus")
Meta Description: "This is the Mage Page of <username>. Learn more about them here!"

Downloads Page
http://nexus.codespells.org/downloads
Title: "Downloads | CodeSpells Nexus"
Meta Description: "Download the latest CodeSpells video games. The spells you write here in the Nexus can be cast inside of these games!"
